classes:
  wf:Invoice:
    properties:
      wf:hasInvoiceNumber:
        fibo_equiv: "fibo:invoiceIdentifier"
        aliases: ["invoice number", "invoice no", "invoice#", "inv#", "reference no", "invoice id"]
        type: string
      wf:hasInvoiceDate:
        fibo_equiv: "fibo:dateIssued"
        aliases: ["invoice date", "date of invoice", "issued on", "date:"]
        type: date
      wf:hasInvoiceTotal:
        fibo_equiv: "fibo:totalAmount"
        aliases: ["total due", "amount due", "invoice total", "grand total", "balance due"]
        type: money

  wf:LoanAgreement:
    properties:
      wf:hasBorrower:
        fibo_equiv: "fibo:hasBorrower"
        aliases: ["borrower", "applicant", "customer name", "lessee (loan)"]
        type: party
      wf:hasPrincipalAmount:
        fibo_equiv: "fibo:principalAmount"
        aliases: ["principal", "original amount", "loan amount", "amount financed"]
        type: money
      wf:hasInterestRate:
        fibo_equiv: "fibo:interestRate"
        aliases: ["interest rate", "rate", "apr", "annual percentage rate"]
        type: percent

  wf:LeaseAgreement:
    properties:
      wf:hasLessee:
        fibo_equiv: "fibo:hasLessee"
        aliases: ["lessee", "tenant", "customer name"]
        type: party
      wf:hasTermMonths:
        fibo_equiv: "fibo:term"
        aliases: ["lease term", "term", "months"]
        type: integer

  wf:FundingDetailSheet:
    properties:
      wf:hasGrandTotal:
        fibo_equiv: "fibo:totalAmount"
        aliases: ["grand total", "total funding", "net funded amount", "funding total"]
        type: money
